# Generated by Django 2.2.7 on 2019-12-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_page', '0002_auto_20191220_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingspage',
            name='panel_4',
            field=models.CharField(default='#90ee90', max_length=255),
        ),
    ]
