# Generated by Django 2.2.7 on 2019-12-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_page', '0003_auto_20191221_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingspage',
            old_name='panel_1',
            new_name='panel_1_color',
        ),
        migrations.RenameField(
            model_name='settingspage',
            old_name='panel_2',
            new_name='panel_2_color',
        ),
        migrations.RenameField(
            model_name='settingspage',
            old_name='panel_3',
            new_name='panel_3_color',
        ),
        migrations.RenameField(
            model_name='settingspage',
            old_name='panel_4',
            new_name='panel_4_color',
        ),
        migrations.AddField(
            model_name='settingspage',
            name='panel_1_name',
            field=models.CharField(default='Important', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='panel_2_name',
            field=models.CharField(default='Normal', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='panel_3_name',
            field=models.CharField(default='Later', max_length=255),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='panel_4_name',
            field=models.CharField(default='Done', max_length=255),
        ),
    ]
