# Generated by Django 2.2.7 on 2019-12-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_page', '0005_settingspage_shadow_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingspage',
            name='panel_1_name',
            field=models.CharField(blank=True, default='Important', max_length=255),
        ),
        migrations.AlterField(
            model_name='settingspage',
            name='panel_2_name',
            field=models.CharField(blank=True, default='Normal', max_length=255),
        ),
        migrations.AlterField(
            model_name='settingspage',
            name='panel_3_name',
            field=models.CharField(blank=True, default='Later', max_length=255),
        ),
        migrations.AlterField(
            model_name='settingspage',
            name='panel_4_name',
            field=models.CharField(blank=True, default='Done', max_length=255),
        ),
    ]
