# Generated by Django 2.2 on 2019-11-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191104_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.CharField(default='column2', max_length=255),
        ),
    ]
