# Generated by Django 2.2.7 on 2019-12-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_tasks_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='order_no',
            field=models.IntegerField(default=99),
        ),
    ]
